import { Inter } from 'next/font/google';
import type { Metadata } from 'next';
import Provider from '@/app/Provider';
import { ReactNode } from 'react';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="light">
      <body className={inter.className}>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
